//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendingMachineCoins
    {
        public int id { get; set; }
        public int VendingMachineCoins1 { get; set; }
        public int Coinsld { get; set; }
        public int Count { get; set; }
        public int isActive { get; set; }
    
        public virtual Coins Coins { get; set; }
        public virtual VendingMachines VendingMachines { get; set; }
    }
}
